[package]
name = "azure-functions"
license = "MIT"
version = "0.1.5"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
description = "Azure Functions for Rust"
repository = "https://github.com/peterhuene/azure-functions-rs/"

[dependencies]
azure-functions-shared = { version = "0.1.5", path = "../azure-functions-shared" }
azure-functions-codegen = { version = "0.1.5", path = "../azure-functions-codegen" }
log = "0.4.2"
grpcio = "0.3.0"
futures = "0.1.16"
clap = "2.31.2"
tokio-threadpool = "0.1.3"
serde = "1.0.66"
serde_json = "1.0.20"
serde_derive = "1.0.66"
chrono = { version = "0.4.4", features = ["serde"] }

[dev-dependencies]
matches = "0.1.7"