[package]
name = "azure-functions"
license = "MIT"
version = "0.9.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
description = "Azure Functions for Rust"
repository = "https://github.com/peterhuene/azure-functions-rs/"
homepage = "https://functions.rs"
edition = "2018"

[dependencies]
azure-functions-shared = { version = "0.9.0", path = "../azure-functions-shared" }
azure-functions-codegen = { version = "0.9.0", path = "../azure-functions-codegen" }
http = "0.1"
tower-hyper = "0.1.0"
tower-grpc = "0.1.0"
tower-service = "0.2.0"
tower-util = "0.1.0"
log = { version = "0.4.6", features = ["std"] }
futures = "0.1.27"
clap = "2.33.0"
tokio = "0.1.21"
serde = "1.0.93"
serde_json = "1.0.39"
serde_derive = "1.0.93"
chrono = { version = "0.4.6", features = ["serde"] }
xml-rs = "0.8.0"
lazy_static = "1.3.0"
tempfile = "3.0.8"
ctrlc = "3.1.3"
backtrace = "0.3.31"
fs_extra = "1.1.0"
semver = "0.9.0"

[features]
unstable = ["azure-functions-codegen/unstable", "azure-functions-shared/unstable"]

[dev-dependencies]
matches = "0.1.8"
