[package]
name = "azure-functions-shared"
license = "MIT"
version = "0.4.1"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
description = "Implementations shared between the azure-functions-codegen and azure-functions crates."
repository = "https://github.com/peterhuene/azure-functions-rs/"
homepage = "https://functions.rs"
edition = "2018"

[dependencies]
azure-functions-shared-codegen = { version = "0.4.1", path = "../azure-functions-shared-codegen" }
protobuf = "2.0.5"
grpcio = { version = "0.4.4", default-features = false, features = ["protobuf-codec"] }
futures = "0.1.24"
serde = "1.0.88"
serde_derive = "1.0.88"
quote = "0.6.11"
syn = { version = "0.15.26", features = ["full"] }
proc-macro2 = { version = "0.4.27" }
cfg-if = "0.1.6"
lazy_static = "1.2.0"

[build-dependencies]
protoc-grpcio = "1.0.1"

[features]
default = []
compile_protobufs = []
