[workspace]

members = [
    "azure-functions",
    "azure-functions-codegen",
    "azure-functions-durable",
    "azure-functions-sdk",
    "azure-functions-shared",
    "azure-functions-shared-codegen"
]
