[workspace]

members = [
    "azure-functions",
    "azure-functions-codegen",
    "azure-functions-shared",
    "azure-functions-shared-codegen",
    "examples/http",
    "examples/timer",
    "examples/queue"
]
