version: 2
jobs:
  build:
    docker:
      - image: peterhuene/azure-functions-rs-ci
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Sync Azure Functions Languge Worker Protobuf
          command: git submodule sync && git submodule update --init
      - run:
          name: Check source formatting
          command: |
            cargo fmt --version || true
            cargo fmt -- --check
            git diff
      - run:
          name: Check for linter errors
          command: |
            cargo clippy --version || true
            # TODO: use cargo clippy -- -Dwarnings once this is merged https://github.com/stepancheg/rust-protobuf/pull/332
            cargo clippy
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Test
          command: cargo test --release
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
  build-ci-image:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker Hub
          command: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      - run:
          name: Build CI Docker image
          command: |
            cd docker/ci
            docker build -t peterhuene/azure-functions-rs-ci:latest .
      - run:
          name: Push CI Docker image
          command: docker push peterhuene/azure-functions-rs-ci:latest
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-ci-image
      - build
