[package]
name = "azure-functions-shared-codegen"
license = "MIT"
version = "0.2.3"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
description = "Azure Functions for Rust shared code generation support."
repository = "https://github.com/peterhuene/azure-functions-rs/"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.10"
syn = { version = "0.15.18", features = ["full"] }
