jobs:
- ${{ each toolchain in parameters.toolchains }}:
  - job: build_${{ toolchain.name }}
    displayName: Build and test with ${{ toolchain.name }} on
    pool:
      vmImage: $(image)
    strategy:
      matrix:
        Linux:
          image: ubuntu-16.04
        macOS:
          image: macos-10.13
        Windows:
          image: vs2017-win2016
    steps:
      - template: ../steps/build-and-test.yml
        parameters:
          toolchain: ${{ toolchain.version }}
          features: ${{ toolchain.features }}
