jobs:
- ${{ each toolchain in parameters.toolchains }}:
  - job: formatting_${{ toolchain.name }}
    displayName: Check source formatting with ${{ toolchain.name }}
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ../steps/check-source-formatting.yml
        parameters:
          toolchain: ${{ toolchain.version }}
