jobs:
- ${{ each toolchain in parameters.toolchains }}:
  - job: linting_${{ toolchain.name }}
    displayName: Check source linting with ${{ toolchain.name }}
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ../steps/check-source-linting.yml
        parameters:
          toolchain: ${{ toolchain.version }}
