jobs:
- ${{ each toolchain in parameters.toolchains }}:
  - job: protobufs_${{ toolchain.name }}
    displayName: Compile protobufs with ${{ toolchain.name }}
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ../steps/compile-protobufs.yml
        parameters:
          version: ${{ parameters.version }}
          toolchain: ${{ toolchain.version }}
          platform: linux-x86_64
